### ISSUE TITLE
Projects not showing in mobile site

### ISSUE THREAD

**Issue by alexjadkins1** [konstantinmuenster/gatsby-theme-portfolio-minimal#5]
First off, thanks a lot for creating a great theme! However, when accessing my site using a mobile device, only the first project in my projects.json appears. I have no idea why this happens as all projects appear when the site is accessed on the computer.

**Comment by konstantinmuenster** [comment]
Hey @alexjadkins1 ! What type of device are you using? On mobile, the projects are displayed in a horizontal slider. It could be that your screen is too narrow so that the second project does not fit into the viewport. 

This is how it should look like:

<img width="392" alt="Bildschirmfoto 2022-01-17 um 20 35 20" src="https://user-images.githubusercontent.com/46243719/149828208-20885087-e658-476c-bfe9-b344a23bc8b8.png">

**Comment by alexjadkins1** [comment]
That was exactly it, thank you.
