### ISSUE TITLE
I Want To Change Background Color of Footer?

### ISSUE THREAD

**Issue by awais-mustafa** [konstantinmuenster/gatsby-theme-portfolio-minimal#51]
I changed in node module footer file, in gatsby-theme-portfolio-minimal. And its working on local server but, when i deployed this local server website to Vercel. Then its download the node modules from server, so its replaced my customization, so any solution because i think its very hard-coded, correct me if i am wrong?

**Comment by sdelorme** [comment]
@awais-mustafa Rather than attempting to change any of the package contents, you should be attempting to _[shadow](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/#extending-shadowed-files)_ since you are using a theme.

With that said, I noticed that there's some inline-styling here that might be making it impossible to override with just shadowing the CSS source file. @konstantinmuenster am I right? Seems like you'd have to also re-write the source Footer component itself?
<img width="550" alt="Screenshot 2023-12-27 at 1 38 58 PM" src="https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/assets/19362487/f2c6dec0-6b70-4602-aa7a-39ed5cf5bcfa">

**Comment by konstantinruge** [comment]
@sdelorme True! Due to the inline styles, you'd need to shadow the Footer component too (given that you want to adapt the inline styles too). But usually, the shadowing should work fine for both, CSS and JS files.
